version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    depends_on:
      - postgres
      - nats
    environment:
      TOKEN: ${TOKEN}
      NATS_URL: "nats://localhost:4222"
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  nats:
    image: nats:2.10
    container_name: nats_server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "-js"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
